export const PRODUCT_DISPONIBILITA = 'product_disponibilità';
export const LABEL = {
  PROD_SCONTO: 'prod_sconto',
  PROD_AVAIL_ONLINE: 'prod_avail_online',
  PROD_AVAIL_STORE: 'prod_avail_store',
  PROD_VARIANT: 'prod_variant',
  PROD_PUNTI_OMAGGIO: 'prod_puntiomaggio',
  PROD_IDEAPIU: 'prod_ideapiu',
  PROD_BUNDLE: 'prod_bundle',
  FILTER_NAME: 'filter_name',
  FILTER_VALUE: 'filter_value',
  FILTER_RESULT: 'filter_result',
  PROD_POSITION: 'prod_position',
  PROD_LIST: 'prod_list',
  PROD_GAMMA: 'prod_gamma',
  PROD_NEW: 'prod_new',
  PROD_PRICE: 'prod_price',
  PROD_ID: 'prod_id',
  PROD_CATEGORY: 'prod_category',
  PAGE_NAME: 'page_name',
  CID: 'cid',
  NAVIGATION_STORE: 'navigation_store',
  APP_RELEASE_VERSION: 'app_release_version',
  EVENT_TYPE: 'event_type',
  EVENT_ACTION: 'event_action'
};
