export const REQUEST_FETCH_WORLD = 'REQUEST_FETCH_WORLD';
export const SUCCESS_FETCH_WORLD = 'SUCCESS_FETCH_WORLD';
export const FAILURE_FETCH_WORLD = 'FAILURE_FETCH_WORLD';

export const REQUEST_FETCH_WEATHER = 'REQUEST_FETCH_WEATHER';
export const SUCCESS_FETCH_WEATHER = 'SUCCESS_FETCH_WEATHER';
export const FAILURE_FETCH_WEATHER = 'FAILURE_FETCH_WEATHER';

export const REQUEST_FETCH_CATEGORY = 'REQUEST_FETCH_CATEGORY';
export const SUCCESS_FETCH_CATEGORY = 'SUCCESS_FETCH_CATEGORY';
export const FAILURE_FETCH_CATEGORY = 'FAILURE_FETCH_CATEGORY';

export const REQUEST_FETCH_PRODUCT = 'REQUEST_FETCH_PRODUCT';
export const SUCCESS_FETCH_PRODUCT = 'SUCCESS_FETCH_PRODUCT';
export const FAILURE_FETCH_PRODUCT = 'FAILURE_FETCH_PRODUCT';

export const UPDATE_CATALOGUE = 'UPDATE_CATALOGUE';

export const IDLE_TIMER_START = 'IDLE_TIMER_START';
export const IDLE_TIMER_RESET = 'IDLE_TIMER_RESET';
export const IDLE_TIMER_COMPLETE = 'IDLE_TIMER_COMPLETE';
