export const REQUEST_FETCH_WORLD = 'REQUEST_FETCH_WORLD';
export const SUCCESS_FETCH_WORLD = 'SUCCESS_FETCH_WORLD';
export const FAILURE_FETCH_WORLD = 'FAILURE_FETCH_WORLD';

export const REQUEST_FETCH_WEATHER = 'REQUEST_FETCH_WEATHER';
export const SUCCESS_FETCH_WEATHER = 'SUCCESS_FETCH_WEATHER';
export const FAILURE_FETCH_WEATHER = 'FAILURE_FETCH_WEATHER';

export const REQUEST_FETCH_CATEGORY = 'REQUEST_FETCH_CATEGORY';
export const SUCCESS_FETCH_CATEGORY = 'SUCCESS_FETCH_CATEGORY';
export const FAILURE_FETCH_CATEGORY = 'FAILURE_FETCH_CATEGORY';
