export const REQUEST_FETCH_WORLD = 'REQUEST_FETCH_WORLD';
export const SUCCESS_FETCH_WORLD = 'SUCCESS_FETCH_WORLD';
export const FAILURE_FETCH_WORLD = 'FAILURE_FETCH_WORLD';

export const REQUEST_FETCH_WEATHER = 'REQUEST_FETCH_WEATHER';
export const SUCCESS_FETCH_WEATHER = 'SUCCESS_FETCH_WEATHER';
export const FAILURE_FETCH_WEATHER = 'FAILURE_FETCH_WEATHER';

export const REQUEST_FETCH_CATEGORY = 'REQUEST_FETCH_CATEGORY';
export const SUCCESS_FETCH_CATEGORY = 'SUCCESS_FETCH_CATEGORY';
export const FAILURE_FETCH_CATEGORY = 'FAILURE_FETCH_CATEGORY';

export const REQUEST_FETCH_PRODUCT = 'REQUEST_FETCH_PRODUCT';
export const SUCCESS_FETCH_PRODUCT = 'SUCCESS_FETCH_PRODUCT';
export const FAILURE_FETCH_PRODUCT = 'FAILURE_FETCH_PRODUCT';

export const REQUEST_FETCH_PRODUCTLIST = 'REQUEST_FETCH_PRODUCTLIST';
export const SUCCESS_FETCH_PRODUCTLIST = 'SUCCESS_FETCH_PRODUCTLIST';
export const FAILURE_FETCH_PRODUCTLIST = 'FAILURE_FETCH_PRODUCTLIST';

export const IDLE_TIMER_START = 'IDLE_TIMER_START';
export const IDLE_TIMER_RESET = 'IDLE_TIMER_RESET';
export const IDLE_TIMER_COMPLETE = 'IDLE_TIMER_COMPLETE';

export const SET_STORE_CODE = 'SET_STORE_CODE';
export const SUCCESS_FETCH_STORE = 'SUCCESS_FETCH_STORE';
export const FAILURE_FETCH_STORE = 'FAILURE_FETCH_STORE';

export const REQUEST_FETCH_NEARBYSTORES = 'REQUEST_FETCH_NEARBYSTORES';
export const SUCCESS_FETCH_NEARBYSTORES = 'SUCCESS_FETCH_NEARBYSTORES';
export const FAILURE_FETCH_NEARBYSTORES = 'FAILURE_FETCH_NEARBYSTORES';

export const REQUEST_FETCH_RELATEDPRODUCTS = 'REQUEST_FETCH_RELATEDPRODUCTS';
export const SUCCESS_FETCH_RELATEDPRODUCTS = 'SUCCESS_FETCH_RELATEDPRODUCTS';
export const FAILURE_FETCH_RELATEDPRODUCTS = 'FAILURE_FETCH_RELATEDPRODUCTS';

export const REQUEST_FETCH_XSELLPRODUCTS = 'REQUEST_FETCH_XSELLPRODUCTS';
export const SUCCESS_FETCH_XSELLPRODUCTS = 'SUCCESS_FETCH_XSELLPRODUCTS';
export const FAILURE_FETCH_XSELLPRODUCTS = 'FAILURE_FETCH_XSELLPRODUCTS';

export const REQUEST_FETCH_STORESTOCK = 'REQUEST_FETCH_STORESTOCK';
export const SUCCESS_FETCH_STORESTOCK = 'SUCCESS_FETCH_STORESTOCK';
export const FAILURE_FETCH_STORESTOCK = 'FAILURE_FETCH_STORESTOCK';
