export const clearSky = 'clear sky';
export const fewClouds = 'few clouds';
export const scatteredClouds = 'scattered clouds';
export const brokenClouds = 'broken clouds';
export const showerRain = 'shower rain';
export const rain = 'rain';
export const thunderstorm = 'thunderstorm';
export const snow = 'snow';
export const mist = 'mist';
